spring:
  profiles:
    active:
      - cat
      - ES
      - prod
guru:
  username: YmlSuperuser
  password: YmlDBPassword
  jdbcurl: YmlSomeUrlForDB

---
spring:
  profiles: prod
guru:
  username: YmlProdSuperuser
  password: YmlProdDBPassword
  jdbcurl: YmlProdSomeUrlForDB